### ISSUE TITLE
Character not loaded

### ISSUE THREAD

**Issue by jesus2099** [Violentmonkey/Violentmonkey-oex#37]
Hello,
I have spotted a (minor issue) with [fast-cancel-edits.user.js](https://bitbucket.org/mwiencek/userscripts/raw/master/fast-cancel-edits.user.js):

* Try the URL when Violentmonkey is disabled : the quote characters “” (`U+201C` and `U+201D`) are OK.
* Now try the URL when Violentmonkey is enabled : those characters are replace with �� (`U+FFFD` REPLACEMENT CHARACTER) once loaded in the installation editor/confirm.

If it’s difficult to solve, just never mind for the moment, as I have scripts with many more characters that load **OK**. So maybe this script is only using two special characters and that’s why.

**Comment by gera2ld** [comment]
You can see the highlighted source code here: <https://bitbucket.org/mwiencek/userscripts/src/cd643f7045a0875f56cebc30b396cf2236052c6b/fast-cancel-edits.user.js>. The problem is there in the source code, maybe something about encodings or HTML entities. I don't think there is anything to do with Violentmonkey.

**Comment by jesus2099** [comment]
There is no html entities in the source code...
It opens OK with the RAW button and when you download the script in an editor (the link in my original post). Maybe bit bucket stuff is not served properly, not in UTF-8 or something...
I'll research too. I'll tell you if I have an idea...

**Comment by jesus2099** [comment]
You were right, @gera2ld :)
https://bitbucket.org/mwiencek/userscripts/pull-requests/19
